# Generated by Django 5.0.7 on 2025-06-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_producto_descripcion'),
    ]

    operations = [
    ]
