# Generated by Django 5.0.7 on 2025-06-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('veterinario', 'Veterinario')], default='veterinario', max_length=20, verbose_name='Rol'),
        ),
    ]
