# Generated by Django 5.0.7 on 2025-07-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfilusuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='password_visible',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Contraseña visible'),
        ),
    ]
