# Generated by Django 5.0.7 on 2025-06-30 05:13

import consultas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_alter_imagendiagnostica_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagendiagnostica',
            name='archivo',
            field=models.FileField(upload_to=consultas.models.ImagenDiagnostica.upload_to),
        ),
    ]
