# Generated by Django 5.0.7 on 2025-07-21 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_alter_imagendiagnostica_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='programada',
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='consultas.cita'),
        ),
    ]
