# Generated by Django 5.2.6 on 2025-09-30 05:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0006_remove_cita_fecha_creacion_remove_cita_programada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagendiagnostica',
            name='archivo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='archivo'),
        ),
    ]
