# Generated by Django 5.0.7 on 2025-07-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_mascota_activa_alter_mascota_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
