# Generated by Django 5.2.6 on 2025-09-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_mascota_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='esterilizado',
            field=models.CharField(choices=[('N', 'No esterilizado'), ('S', 'Esterilizado'), ('P', 'Programado para esterilizar')], default='N', help_text='Estado de esterilización de la mascota', max_length=1),
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_esterilizacion',
            field=models.DateField(blank=True, help_text='Fecha en que fue esterilizada la mascota (opcional)', null=True),
        ),
    ]
