# Generated by Django 5.2.6 on 2025-09-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_mascota_esterilizado_mascota_fecha_esterilizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pets/profiles/'),
        ),
    ]
